### ISSUE TITLE
Landing page Navbar and Footer Design

### ISSUE THREAD

**Issue by jagdish4501** [swiftnotifier/dokaai-documentation#1]
https://www.figma.com/design/AIPCWYlaxBjsOp6xIHsAvg/Dev-Handoff-(new)?node-id=1323-22415&node-type=section&t=ZWtaU55S6Mw9R0mC-0

**Comment by ajoshi31** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error In Invite is not going after a long timer](https://trello.com/c/wfhlGh8R/1-error-in-invite-is-not-going-after-a-long-timer)
